server:
  port: 8083


spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**

        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comments/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true  # This service does not register with Eureka
    fetch-registry: true  # This service does not fetch the registry from Eureka
  server:
    port: 8761  # Port for the Eureka server

