server:
  port: 8761  # Eureka server port

spring:
  application:
    name: EUREKA-SERVER  # Name of the Eureka server application

eureka:
  client:
    register-with-eureka: false  # Eureka server does not need to register with itself
    fetch-registry: false  # Eureka server does not need to fetch the registry
