spring:
  application:
    name: COMMENT-SERVICE  # Name of the application

  data:
    mongodb:
      uri: mongodb://localhost:27017/commentdb  # MongoDB connection string
      database: commentdb  # MongoDB database name (optional if included in the URI)

server:
  port: 8082  # Port for the COMMENT-SERVICE

eureka:
  instance:
    prefer-ip-address: true  # Use IP address for registration
  client:
    fetch-registry: true  # Fetch the registry from Eureka
    register-with-eureka: true  # Register this service with Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka server
